services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Kinulab\ProcessMonitoringBundle\Monitor\:
        resource: '../../Monitor/*'
        arguments:
            $processes: !tagged monitor.process