services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Kinulab\ProcessMonitoringBundle\Command\:
        resource: '../../Command/*'
        tags: [ 'console.command' ]

    Kinulab\ProcessMonitoringBundle\Monitor\:
        resource: '../../Monitor/*'
        arguments:
            $services: !tagged monitored.service