services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Kinulab\ProcessMonitoringBundle\Monitor\:
        resource: '../../Monitor/*'
        arguments:
            $services: !tagged monitored.service