language: php
dist: trusty
sudo: false

php:
    - 7.0
    - 7.1

env:
  - SYMFONY_VERSION=3.4.*

before_script:
  - composer config -g github-oauth.github.com ${OAUTHTOKEN}
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --prefer-dist --no-interaction --prefer-stable

script: phpunit
