language: php
dist: trusty
sudo: false

php:
    - 7.0
    - 7.1
    - 7.2

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*@dev

matrix:
  exclude:
    - php: 7.0
      env: SYMFONY_VERSION=4.0.*
    - php: 7.0
      env: SYMFONY_VERSION=4.1.*@dev

before_script:
  - composer config -g github-oauth.github.com ${OAUTHTOKEN}
  - composer require symfony/process:${SYMFONY_VERSION} --no-update
  - composer require symfony/monolog-bridge:${SYMFONY_VERSION} --no-update
  - composer require symfony/event-dispatcher:${SYMFONY_VERSION} --no-update
  - composer update --prefer-dist --no-interaction --prefer-stable
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
  - chmod +x php-coveralls.phar

script: phpunit

after_success:
  - travis_retry php php-coveralls.phar -v
